parameters:
  app.event.orm.event_listener.dir: '%kernel.project_dir%/src/Event/ORM/EventListener'

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Event\ORM\EntityListener\:
    resource: '../../src/Event/ORM/EntityListener/*'
    tags:
      - name: doctrine.orm.entity_listener