services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Import\:
    resource: '../../src/Import/*'
    exclude:  '../../src/Import/{Exception}'

  App\Import\Processor\:
    resource: '../../src/Import/Processor/*'
    public:   true
    exclude:  '../../src/Import/Processor/{Parser,Result}'

  App\Import\Reader\:
    resource: '../../src/Import/Reader/*'
    public:   true
    exclude: '../../src/Import/Reader/{Result}'

  App\Import\Writer\:
    resource: '../../src/Import/Writer/*'
    public:   true