services:
  App\Lifecycle\Entity\DatedEntityLifecycleListener:
    tags:
      - name: doctrine.event_listener
        event: prePersist
      - name: doctrine.event_listener
        event: preUpdate


  App\Lifecycle\Entity\RefreshedEntityLifecycleListener:
    tags:
      - name: doctrine.event_listener
        event: postLoad

  App\Lifecycle\Entity\OwnedEntityLifecycleListener:
    autowire: true
    tags:
      - name: doctrine.event_listener
        event: prePersist

  App\Lifecycle\Entity\Budget\BudgetLifecycleListener:
    tags:
      - name: doctrine.orm.entity_listener
        event: prePersist
        entity: App\Entity\Budget\Budget

  App\Lifecycle\Entity\Transaction\TransactionLifecycleListener:
    tags:
      - name: doctrine.event_listener
        event: postPersist
      - name: doctrine.event_listener
        event: postRemove
      - name: doctrine.event_listener
        event: postUpdate
      - name: doctrine.event_listener
        event: prePersist
      - name: doctrine.event_listener
        event: preUpdate
      - name: doctrine.event_listener
        event: preRemove