parameters:
    env(DATABASE_HOST): database
    env(DATABASE_DRIVER): pdo_pgsql
    env(DATABASE_PORT): 5432
    env(DATABASE_CHARSET): UTF8

doctrine:
    dbal:
        dbname:         '%env(resolve:DATABASE_NAME)%'
        host:           '%env(resolve:DATABASE_HOST)%'
        port:           '%env(resolve:DATABASE_PORT)%'
        user:           '%env(resolve:DATABASE_USER)%'
        password:       '%env(resolve:DATABASE_PASSWORD)%'
        driver:         '%env(resolve:DATABASE_DRIVER)%'
        charset:        '%env(resolve:DATABASE_CHARSET)%'
        server_version: '%env(resolve:DATABASE_VERSION)%'

    orm:
        auto_generate_proxy_classes: true
        auto_mapping: true
        dql:
            string_functions:
                YEAR: DoctrineExtensions\Query\Sqlite\Year
                MONTH: DoctrineExtensions\Query\Sqlite\Month
                DAY: DoctrineExtensions\Query\Sqlite\Day
                HOUR: DoctrineExtensions\Query\Sqlite\Hour
                MINUTE: DoctrineExtensions\Query\Sqlite\Minute
                SECOND: DoctrineExtensions\Query\Sqlite\Second
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware