parameters:
    env(DATABASE_HOST): database
    env(DATABASE_DRIVER): pdo_pgsql
    env(DATABASE_PORT): 5432
    env(DATABASE_CHARSET): UTF8

doctrine:
    dbal:
        dbname:         '%env(resolve:DATABASE_NAME)%'
        host:           '%env(resolve:DATABASE_HOST)%'
        port:           '%env(resolve:DATABASE_PORT)%'
        user:           '%env(resolve:DATABASE_USER)%'
        password:       '%env(resolve:DATABASE_PASSWORD)%'
        driver:         '%env(resolve:DATABASE_DRIVER)%'
        charset:        '%env(resolve:DATABASE_CHARSET)%'
        server_version: '%env(resolve:DATABASE_VERSION)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App