sonata_admin:
  title: 'Sonata Admin'
  dashboard:
    blocks: []

    groups:
      Account:
        icon: 'fas fa-university'
      Schedule:
        icon: 'fas fa-clock'
      Budget:
        icon: 'fas fa-piggy-bank'
      ThirdParty:
        icon: 'fas fa-users'
      Settings:
        icon: 'fas fa-cogs'

  templates:
    dashboard: 'dashboard/dashboard.html.twig'
    layout: 'base.html.twig'
