sonata_admin:
    title: 'Sonata Admin'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }

        groups:
            Account:
                icon: 'fas fa-piggy-bank'
            Settings:
                icon: 'fas fa-cogs'


    templates:
        layout: 'base.html.twig'

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
