version: "3.7"

services:
  php:
    image: neimheadh/bank-api-php:${PHP_VERSION:-8.2}
    container_name: bank_middleware_php
    depends_on:
      - database
    networks:
      - back
    volumes:
      - .:/var/www/html
      - ~/.ssh:/home/developer/.ssh:ro
      - ~/.composer:/home/developer/.composer

  database:
    image: postgres:${DATABASE_VERSION}-alpine
    container_name: bank_middleware_database
    networks:
      - back
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
    volumes:
      - db_data:/var/lib/postgresql/data:rw

  nginx:
    image: nginx:${NGINX_VERSION:-latest}
    container_name: bank_middleware_nginx
    depends_on:
      - php
    networks:
      - back
      - reverse-proxy
    working_dir: /var/www/html
    labels:
      - traefik.enable=true
      - traefik.http.routers.bank_middleware_nginx.rule=Host(`bank-middleware.docker.localhost`)
      - traefik.http.routers.bank_middleware_nginx.middlewares=redirecthttps@file
      - traefik.docker.network=reverse-proxy
    volumes:
      - .:/var/www/html
      - ./docker/nginx/config.conf:/etc/nginx/conf.d/default.conf:ro

  node:
    image: node:${NODE_VERSION:-lts}
    container_name: bank_middleware_node
    user: ${USER_ID:-1000}:${GROUP_ID:-1000}
    command:
      - yarn
      - watch
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html

networks:
  reverse-proxy:
    external: true
  back:
    driver: bridge

volumes:
  db_data: 
    name: bank_middleware_database_data